package com.example.epub.selection;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "selections")
public class Selection {
    public static final String COL_PAGE = "pageNumber";
    public static final String COL_FILE_NAME = "fileName";
    public static final String COL_START = "start";
    public static final String COL_END = "end";
    public static final String COL_NOTE = "note";
    public static final String COL_TEXT = "text";
    public static final String START_VERSE_NUMBER = "start_verse_number";
    public static final String END_VERSE_NUMBER = "end_verse_number";
    public static final String COL_COLOR = "color";

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    private int id;
    @DatabaseField(columnName = COL_START)
    private int start;
    @DatabaseField(columnName = COL_END)
    private int end;
    @DatabaseField(columnName = START_VERSE_NUMBER)
    private int startVerseNumber;
    @DatabaseField(columnName = END_VERSE_NUMBER)
    private int endVerseNumber;
    @DatabaseField(columnName = COL_COLOR)
    private String color = SelectionColor.INITIAL;
    @DatabaseField(columnName = COL_PAGE)
    private int pageNumber;
    @DatabaseField(columnName = COL_FILE_NAME)
    private String fileName;

    @DatabaseField(columnName = COL_TEXT)
    private String text;

    private int fontSize;

    @DatabaseField(columnName = COL_NOTE)
    private String note;

    public Selection() {
        // needed by ormlite
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getEnd() {
        return end;
    }

    public void setEnd(int end) {
        this.end = end;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public int getPageNumber() {
        return pageNumber;
    }

    public void setPageNumber(int pageNumber) {
        this.pageNumber = pageNumber;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public int getFontSize() {
        return fontSize;
    }

    public void setFontSize(int fontSize) {
        this.fontSize = fontSize;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public int getStartVerseNumber() {
        return startVerseNumber;
    }

    public void setStartVerseNumber(int startVerseNumber) {
        this.startVerseNumber = startVerseNumber;
    }

    public int getEndVerseNumber() {
        return endVerseNumber;
    }

    public void setEndVerseNumber(int endVerseNumber) {
        this.endVerseNumber = endVerseNumber;
    }
}
